# Generated by Django 4.1.2 on 2022-10-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemodel',
            name='creaedAt',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='currentStepId',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='countryOfOrigin',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
