# Generated by Django 4.1.2 on 2022-10-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0002_candidatemodel_creaedat_resultmodel_currentstepid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='currentStepName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='idCandidate',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='idJob',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='identificationDocument',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='lastName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='linkedinProfileUrl',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='manualCandidate',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='mobileNumber',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='nameJob',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='score',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
