# Generated by Django 4.1.2 on 2022-10-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0004_resultmodel_currentstepstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualcandidatemodel',
            name='manualCandidate',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='manualCandidate',
        ),
    ]
