# Generated by Django 4.1.2 on 2022-10-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0005_remove_manualcandidatemodel_manualcandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='manualCandidate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
