# Generated by Django 4.1.2 on 2022-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0007_alter_candidatemodel_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='birthdate',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='countryOfOrigin',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='currentStepId',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='currentStepName',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='currentStepStatus',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='idCandidate',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='idJob',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='identificationDocument',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='lastName',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='linkedinProfileUrl',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='manualCandidate',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='mobileNumber',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='nameJob',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='result_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='score',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
