# Generated by Django 4.1.2 on 2022-10-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0008_alter_resultmodel_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='birthdate',
            new_name='Candidate_birthdate',
        ),
    ]
