# Generated by Django 4.1.2 on 2022-10-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0009_rename_birthdate_resultmodel_candidate_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='idCandidate',
            new_name='Candidate_Id',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='idJob',
            new_name='Job_Id',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='nameJob',
            new_name='Job_Name',
        ),
    ]
