# Generated by Django 4.1.2 on 2022-10-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0010_rename_idcandidate_resultmodel_candidate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='Candidate_Id',
            new_name='candidate_Id',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='Candidate_birthdate',
            new_name='candidate_birthdate',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='Job_Id',
            new_name='job_Id',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='Job_Name',
            new_name='job_Name',
        ),
    ]
