# Generated by Django 4.1.2 on 2022-10-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0011_rename_candidate_id_resultmodel_candidate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='email',
            new_name='candidate_email',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='gender',
            new_name='candidate_gender',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='identificationDocument',
            new_name='candidate_identificationDocument',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='lastName',
            new_name='candidate_lastName',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='mobileNumber',
            new_name='candidate_mobileNumber',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='name',
            new_name='candidate_name',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='phoneNumber',
            new_name='candidate_phoneNumber',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='score',
            new_name='candidate_score',
        ),
    ]
