# Generated by Django 4.1.2 on 2022-10-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupy', '0012_rename_email_resultmodel_candidate_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_identificationDocument',
            new_name='identificationDocument',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_lastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_mobileNumber',
            new_name='mobileNumber',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_phoneNumber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='candidate_score',
            new_name='score',
        ),
    ]
